//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppStoreIntegrationServiceCore {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServiceResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppStoreIntegrationServiceCore.ServiceResource", typeof(ServiceResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;The value for &lt;b&gt;{0}&lt;/b&gt; was changed from &lt;i&gt;[{1}]&lt;/i&gt; to &lt;i&gt;[{2}]&lt;/i&gt;&lt;/li&gt;.
        /// </summary>
        public static string ArrayLogString {
            get {
                return ResourceManager.GetString("ArrayLogString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPSTOREINTEGRATION_BLOBNAME.
        /// </summary>
        public static string BlobName {
            get {
                return ResourceManager.GetString("BlobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPSTOREINTEGRATION_COMMENTSFILENAME.
        /// </summary>
        public static string CommentsFileName {
            get {
                return ResourceManager.GetString("CommentsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] FontNames {
            get {
                object obj = ResourceManager.GetObject("FontNames", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPSTOREINTEGRATION_LOCAL_FOLDERPATH.
        /// </summary>
        public static string LocalFolderPath {
            get {
                return ResourceManager.GetString("LocalFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPSTOREINTEGRATION_LOGSFILENAME.
        /// </summary>
        public static string LogsFileName {
            get {
                return ResourceManager.GetString("LogsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;The value for &lt;b&gt;{0}&lt;/b&gt; was changed from &lt;i&gt;{1}&lt;/i&gt; to &lt;i&gt;{2}&lt;/i&gt;&lt;/li&gt;.
        /// </summary>
        public static string LogString {
            get {
                return ResourceManager.GetString("LogString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPSTOREINTEGRATION_MAPPINGFILENAME.
        /// </summary>
        public static string MappingFileName {
            get {
                return ResourceManager.GetString("MappingFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;{0}&lt;/b&gt; made a change to {1} at {2}&lt;br&gt;&lt;br&gt;&lt;p&gt;The following changes occured:&lt;/p&gt;&lt;ul&gt;{3}&lt;/ul&gt;.
        /// </summary>
        public static string NewPluginLogString {
            get {
                return ResourceManager.GetString("NewPluginLogString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;{0}&lt;/b&gt; made a change to this plugin at {1}&lt;br&gt;&lt;br&gt;&lt;p&gt;The version with number {2} has changed:&lt;/p&gt;&lt;ul&gt;{3}&lt;/ul&gt;.
        /// </summary>
        public static string NewVersionLogString {
            get {
                return ResourceManager.GetString("NewVersionLogString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPSTOREINTEGRATION_PLUGINSFILENAME.
        /// </summary>
        public static string PluginsFileName {
            get {
                return ResourceManager.GetString("PluginsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPSTOREINTEGRATION_SETTINGSFILENAME.
        /// </summary>
        public static string SettingsFileName {
            get {
                return ResourceManager.GetString("SettingsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPSTOREINTEGRATION_STORAGE_ACCOUNTKEY.
        /// </summary>
        public static string StorageAccountKey {
            get {
                return ResourceManager.GetString("StorageAccountKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPSTOREINTEGRATION_STORAGE_ACCOUNTNAME.
        /// </summary>
        public static string StorageAccountName {
            get {
                return ResourceManager.GetString("StorageAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPINSIGHTS_INSTRUMENTATIONKEY.
        /// </summary>
        public static string TelemetryInstrumentationKey {
            get {
                return ResourceManager.GetString("TelemetryInstrumentationKey", resourceCulture);
            }
        }
    }
}
