//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppStoreIntegrationServiceManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TemplateResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TemplateResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppStoreIntegrationServiceManagement.TemplateResource", typeof(TemplateResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;{0}&lt;/b&gt; accepted the changes for &lt;b&gt;{1}&lt;/b&gt; at {2}.
        /// </summary>
        public static string ApprovedPluginLog {
            get {
                return ResourceManager.GetString("ApprovedPluginLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;{0}&lt;/b&gt; approved the changes for the version with number &lt;b&gt;{1}&lt;/b&gt; at {2}.
        /// </summary>
        public static string ApprovedVersionLog {
            get {
                return ResourceManager.GetString("ApprovedVersionLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;{0}&lt;/b&gt; accepted deletion for &lt;b&gt;{1}&lt;/b&gt; at {2}.
        /// </summary>
        public static string DeletionAcceptedLog {
            get {
                return ResourceManager.GetString("DeletionAcceptedLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;{0}&lt;/b&gt; rejected deletion for &lt;b&gt;{1}&lt;/b&gt; at {2}.
        /// </summary>
        public static string DeletionRejectedLog {
            get {
                return ResourceManager.GetString("DeletionRejectedLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;{0}&lt;/b&gt; requested deletion for &lt;b&gt;{1}&lt;/b&gt; at {2}.
        /// </summary>
        public static string DeletionRequestLog {
            get {
                return ResourceManager.GetString("DeletionRequestLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] FontNames {
            get {
                object obj = ResourceManager.GetObject("FontNames", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;body style=&quot;border: 1px solid lightgray; padding: 20px;&quot;&gt;
        ///&lt;div style=&quot;text-align: center;&quot;&gt;{0}&lt;/div&gt;
        ///&lt;div style=&quot;text-align: center;&quot;&gt;&lt;strong&gt;&amp;nbsp;&lt;/strong&gt;&lt;/div&gt;
        ///&lt;div style=&quot;text-align: center;&quot;&gt;&lt;strong&gt;{1}&lt;/strong&gt;&lt;/div&gt;
        ///&lt;div style=&quot;text-align: center;&quot;&gt;&lt;strong&gt;&amp;nbsp;&lt;/strong&gt;&lt;/div&gt;
        ///&lt;div style=&quot;text-align: center;&quot;&gt;Your profile was associated to the following account:&lt;/div&gt;
        ///&lt;div style=&quot;text-align: center;&quot;&gt;&lt;strong&gt;&amp;nbsp;&lt;/strong&gt;&lt;/div&gt;
        ///&lt;div style=&quot;text-align: center;&quot;&gt;&lt;strong&gt;{2}&lt;/strong&gt;&lt;/div&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NewAccountEmailNotification {
            get {
                return ResourceManager.GetString("NewAccountEmailNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;{0}&lt;/b&gt; added {1} at {2}&lt;br&gt;&lt;br&gt;&lt;p&gt;The plugin properties are:&lt;/p&gt;&lt;ul&gt;{3}&lt;/ul&gt;.
        /// </summary>
        public static string NewPluginLog {
            get {
                return ResourceManager.GetString("NewPluginLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;{0}&lt;/b&gt; changed the status to &lt;i&gt;Active&lt;/i&gt; for &lt;b&gt; {1} &lt;/b&gt; at {2}.
        /// </summary>
        public static string PluginActiveLog {
            get {
                return ResourceManager.GetString("PluginActiveLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;{0}&lt;/b&gt; changed the status to &lt;i&gt;Inactive&lt;/i&gt; for &lt;b&gt;{1}&lt;/b&gt; at {2}.
        /// </summary>
        public static string PluginInactiveLog {
            get {
                return ResourceManager.GetString("PluginInactiveLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;{0}&lt;/b&gt; removed &lt;b&gt;{1}&lt;/b&gt; at {2}.
        /// </summary>
        public static string PluginRemovedLog {
            get {
                return ResourceManager.GetString("PluginRemovedLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;body style=&quot;border: 1px solid lightgray; padding:20px; width: 500px&quot;&gt;
        ///&lt;div style=&quot;text-align: center;&quot;&gt;&lt;b&gt;New&lt;/b&gt;{0}&lt;/div&gt;
        ///&lt;div style=&quot;text-align: center;&quot;&gt;&lt;b&gt;&lt;br&gt;&lt;/b&gt;&lt;/div&gt;
        ///&lt;div style=&quot;text-align: center;&quot;&gt;&lt;img src=&quot;{1}&quot; width=&quot;250&quot;&gt;&lt;/div&gt;
        ///&lt;div style=&quot;text-align: center;&quot;&gt;&lt;br&gt;&lt;/div&gt;
        ///&lt;div style=&quot;text-align: center;&quot;&gt;&lt;b&gt;{2}&lt;/b&gt;&lt;/div&gt;
        ///&lt;div style=&quot;text-align: center;&quot;&gt;&lt;b&gt;&lt;br&gt;&lt;/b&gt;&lt;/div&gt;
        ///&lt;div style=&quot;text-align: center;&quot;&gt;&lt;a href=&quot;{3}&quot;&gt;View&lt;/a&gt;&lt;b&gt;&lt;br&gt;&lt;/b&gt;&lt;/div&gt;
        ///&lt;/body&gt;.
        /// </summary>
        public static string PluginUpdateEmailNotification {
            get {
                return ResourceManager.GetString("PluginUpdateEmailNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;{0}&lt;/b&gt; made changes to {1} at {2}&lt;br&gt;&lt;br&gt;&lt;p&gt;The following changes occured:&lt;/p&gt;&lt;ul&gt;{3}&lt;/ul&gt;.
        /// </summary>
        public static string PluginUpdateLog {
            get {
                return ResourceManager.GetString("PluginUpdateLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;d-flex p-3 border-bottom&quot; style=&quot;width: 400px;&quot;&gt;
        ///&lt;div class=&quot;d-flex flex-column pe-3 border-end&quot;&gt;
        ///&lt;img src=&quot;{0}&quot; width=&quot;50&quot; /&gt;
        ///&lt;p class=&quot;m-0 text-center fw-bold&quot; style=&quot;font-size: 10px;&quot;&gt;{1}&lt;/p&gt;
        ///&lt;/div&gt;
        ///&lt;div class=&quot;w-100 ps-3&quot;&gt;
        ///&lt;p class=&quot;m-0&quot;&gt;{2}&lt;/p&gt;
        ///&lt;a class=&quot;text-decoration-none&quot; href=&quot;{3}&quot;&gt;View&lt;/a&gt;
        ///&lt;p class=&quot;m-0 text-end&quot; style=&quot;font-size: 12px;&quot;&gt;{4}&lt;/p&gt;
        ///&lt;/div&gt;
        ///&lt;/div&gt;.
        /// </summary>
        public static string PushNotificationTemplate {
            get {
                return ResourceManager.GetString("PushNotificationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;{0}&lt;/b&gt; rejected the changes for &lt;b&gt;{1}&lt;/b&gt; at {2}.
        /// </summary>
        public static string RejectedPluginLog {
            get {
                return ResourceManager.GetString("RejectedPluginLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;{0}&lt;/b&gt; rejected the changes for the version with number &lt;b&gt;{1}&lt;/b&gt; at {2}.
        /// </summary>
        public static string RejectedVersionLog {
            get {
                return ResourceManager.GetString("RejectedVersionLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;{0} &lt;/b&gt; changed the status to &lt;i&gt;Active&lt;/i&gt; for the version with number &lt;b&gt;{1}&lt;/b&gt; at {2}.
        /// </summary>
        public static string VersionActiveLog {
            get {
                return ResourceManager.GetString("VersionActiveLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;{0}&lt;/b&gt; accepted the deletion request for version with number &lt;b&gt;{1}&lt;/b&gt; at {2}.
        /// </summary>
        public static string VersionDeletionAcceptedLog {
            get {
                return ResourceManager.GetString("VersionDeletionAcceptedLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;{0}&lt;/b&gt; rejected the deletion request for version with number &lt;b&gt;{1}&lt;/b&gt; at {2}.
        /// </summary>
        public static string VersionDeletionRejectedLog {
            get {
                return ResourceManager.GetString("VersionDeletionRejectedLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;{0}&lt;/b&gt; sent a deletion request for version with number &lt;b&gt;{1}&lt;/b&gt; at {2}.
        /// </summary>
        public static string VersionDeletionRequestLog {
            get {
                return ResourceManager.GetString("VersionDeletionRequestLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;{0} &lt;/b&gt; changed the status to &lt;i&gt;Inactive&lt;/i&gt; for the version with number &lt;b&gt;{1}&lt;/b&gt; at {2}.
        /// </summary>
        public static string VersionInactiveLog {
            get {
                return ResourceManager.GetString("VersionInactiveLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;{0}&lt;/b&gt; removed the version with number &lt;b&gt;{1}&lt;/b&gt; at {2}.
        /// </summary>
        public static string VersionRemovedLog {
            get {
                return ResourceManager.GetString("VersionRemovedLog", resourceCulture);
            }
        }
    }
}
