//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppStoreIntegrationServiceManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TemplateResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TemplateResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppStoreIntegrationServiceManagement.TemplateResource", typeof(TemplateResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] FontNames {
            get {
                object obj = ResourceManager.GetObject("FontNames", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;body style=&quot;font-family: Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, Liberation Sans, sans-serif;&quot;&gt;
        ///    &lt;div style=&quot;background-color: #f8f9fa; border: 1px solid #dee2e6; width: 40%;&quot;&gt;
        ///        &lt;p style=&quot;text-align: center; margin:0;background-color: white;width: 100%;&quot;&gt;
        ///          &lt;img style=&quot;width: 100%;&quot; src=&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAjYAAABZCAMAAAAaVZ6hAAAA3lBMVEX///8AqJ+AgYQAPX98fYB6e36/6OYOq6N3eHvd3d78/PwArKCzs7X4+Pjo6OkApJsAOH6Y2NTT09SHiIqu4+Do9PMAcY6XmJqOj5HAwMLv7/Cqq6y [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NewAccountEmailNotification {
            get {
                return ResourceManager.GetString("NewAccountEmailNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;body style=&quot;font-family: Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, Liberation Sans, sans-serif;&quot;&gt;
        ///    &lt;div style=&quot;background-color: #f8f9fa; border: 1px solid #dee2e6; width: 40%;&quot;&gt;
        ///        &lt;p style=&quot;text-align: center; margin:0;background-color: white;width: 100%;&quot;&gt;
        ///          &lt;img style=&quot;width: 100%;&quot; src=&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAjYAAABZCAMAAAAaVZ6hAAAA3lBMVEX///8AqJ+AgYQAPX98fYB6e36/6OYOq6N3eHvd3d78/PwArKCzs7X4+Pjo6OkApJsAOH6Y2NTT09SHiIqu4+Do9PMAcY6XmJqOj5HAwMLv7/Cqq6y [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PluginUpdateEmailNotification {
            get {
                return ResourceManager.GetString("PluginUpdateEmailNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;body style=&quot;font-family: Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, Liberation Sans, sans-serif;&quot;&gt;
        ///    &lt;div style=&quot;background-color: #f8f9fa; border: 1px solid #dee2e6; width: 40%;&quot;&gt;
        ///        &lt;p style=&quot;text-align: center; margin:0;background-color: white;width: 100%;&quot;&gt;
        ///          &lt;img style=&quot;width: 100%;&quot; src=&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAjYAAABZCAMAAAAaVZ6hAAAA3lBMVEX///8AqJ+AgYQAPX98fYB6e36/6OYOq6N3eHvd3d78/PwArKCzs7X4+Pjo6OkApJsAOH6Y2NTT09SHiIqu4+Do9PMAcY6XmJqOj5HAwMLv7/Cqq6y [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ProfileDeleteEmailNotification {
            get {
                return ResourceManager.GetString("ProfileDeleteEmailNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;d-flex p-3 border-bottom&quot; style=&quot;width: 400px;&quot;&gt;
        ///&lt;div class=&quot;d-flex flex-column pe-3 border-end&quot;&gt;
        ///&lt;img src=&quot;{0}&quot; width=&quot;50&quot; /&gt;
        ///&lt;p class=&quot;m-0 text-center fw-bold&quot; style=&quot;font-size: 10px;&quot;&gt;{1}&lt;/p&gt;
        ///&lt;/div&gt;
        ///&lt;div class=&quot;w-100 ps-3&quot;&gt;
        ///&lt;p class=&quot;m-0&quot;&gt;{2}&lt;/p&gt;
        ///&lt;a class=&quot;text-decoration-none&quot; href=&quot;{3}&quot;&gt;View&lt;/a&gt;
        ///&lt;p class=&quot;m-0 text-end&quot; style=&quot;font-size: 12px;&quot;&gt;{4}&lt;/p&gt;
        ///&lt;/div&gt;
        ///&lt;/div&gt;.
        /// </summary>
        public static string PushNotificationTemplate {
            get {
                return ResourceManager.GetString("PushNotificationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;body style=&quot;font-family: Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, Liberation Sans, sans-serif;&quot;&gt;
        ///    &lt;div style=&quot;background-color: #f8f9fa; border: 1px solid #dee2e6; width: 40%;&quot;&gt;
        ///        &lt;p style=&quot;text-align: center; margin:0;background-color: white;width: 100%;&quot;&gt;
        ///          &lt;img style=&quot;width: 100%;&quot; src=&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAjYAAABZCAMAAAAaVZ6hAAAA3lBMVEX///8AqJ+AgYQAPX98fYB6e36/6OYOq6N3eHvd3d78/PwArKCzs7X4+Pjo6OkApJsAOH6Y2NTT09SHiIqu4+Do9PMAcY6XmJqOj5HAwMLv7/Cqq6y [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RoleUpdateEmailNotification {
            get {
                return ResourceManager.GetString("RoleUpdateEmailNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;body style=&quot;font-family: Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, Liberation Sans, sans-serif; background-color: #F1F2F5;&quot;&gt;
        ///  &lt;table style=&quot;width:100%;&quot;&gt;
        ///    &lt;tbody&gt;
        ///      &lt;tr&gt;
        ///        &lt;td&gt;&lt;/td&gt;
        ///        &lt;td style=&quot;width: 33%; background-color: white;&quot;&gt;
        ///          &lt;table style=&quot;width: 750px;&quot;&gt;
        ///            &lt;tr&gt;
        ///              &lt;td style=&quot;width: 100%;&quot;&gt;
        ///                &lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///                &lt;h1 style=&quot;color: #5D6E7B; margin-left: 20px;&quot;&gt;Added to an RWS Account&lt;/h1&gt;
        ///                &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TestEmail {
            get {
                return ResourceManager.GetString("TestEmail", resourceCulture);
            }
        }
    }
}
